# Site settings
title: Stacky Rocks
logo: img/StackyLogo.png
author-pic: img/faissl-jmt.png
email: your-email@domain.com
url: https://example.github.io
description: > # this means to ignore newlines until "baseurl:"
  Follow the Stacky Rocks for my latest adventures. 
baseurl: /stackyrocks/   # the subpath of your site, e.g. /blog/

# Adventures into the great unknown of technology and the outdoors and leaving Stacky Rock piles to follow.

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#161b1e'
  dk-font: '#35434E'
  lt-font: '#fff'
  logo-font: '#a28859'
  md-font: '#f4eddc'

# Footer settings
footer: Stacky Rocks

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - name: twitter
    title: Twitter
    url: https://twitter.com/LisaFaiss
  - name: github
    title: GitHub
    url: https://github.com/faissl
  - name: linkedin
    title: LinkedIn
    url: https://www.linkedin.com/in/lisafaiss
  - name: youtube
    title: YouTube
    url: https://www.youtube.com/user/LisaFaiss/videos

# Meetups I give a hoot about
meetup-descr: > #ignore newlines untill next "meetup:"
  Where you&#39ll find all the cool kids&#58
meetup:
  - title: Business Intelligence AZ
    url: http://www.meetup.com/businessintelligenceaz/
  - title: Data Science Phoenix
    url: http://www.meetup.com/Data-Science-Phoenix/
  - title: DesertPy Phoenix
    url: http://www.meetup.com/Phoenix-Python-Meetup-Group/
  - title: Phoenix JavaScript
    url: http://www.meetup.com/Phoenix-JavaScript/
  - title: Phoenix Hadood User Group
    url: http://www.meetup.com/Phoenix-Hadoop-User-Group/
  - title: Arizona SQL Server User Group
    url: http://www.meetup.com/Arizona-SQL-Server-User-Group/
  - title: Take a Hike
    url: http://www.meetup.com/Take-a-Hike/


# Build settings
markdown: kramdown
permalink: pretty

