# Site settings
title: Stacky Rocks
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Ducks. Cairns. Stacky Rocks. Whatever you call them they're invaluable wayfinders.
  Stacky Rocks is intended for technological trail-blazing...along with an occasional 
  story about an outdoor adventure. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: LisaFaiss
github_username:  faissl

# Build settings
markdown: kramdown
